### ISSUE TITLE
IndexError: wait set index too big

### ISSUE THREAD

**Issue by dan9thsense** [bdaiinstitute/ros_utilities#57]
When waiting for a service to be ready, using spin_until_future_complete, I occasionally get the error

IndexError: wait set index too big

It only happens when using ros_utilities, so I think it is related to how I am implementing this package.  I saw example given for waiting for transforms and am wondering if I should be doing something similar when waiting for a service to be ready.

[simple_bdai.py-1]   File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/__init__.py", line 254, in spin_until_future_complete
[simple_bdai.py-1]     executor.spin_until_future_complete(future, timeout_sec)
[simple_bdai.py-1]   File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 311, in spin_until_future_complete
[simple_bdai.py-1]     self.spin_once_until_future_complete(future, timeout_left)
[simple_bdai.py-1]   File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 755, in spin_once_until_future_complete
[simple_bdai.py-1]     self._spin_once_impl(timeout_sec)
[simple_bdai.py-1]   File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 737, in _spin_once_impl
[simple_bdai.py-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[simple_bdai.py-1]   File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[simple_bdai.py-1]     return next(self._cb_iter)
[simple_bdai.py-1]   File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/executors.py", line 642, in _wait_for_ready_callbacks
[simple_bdai.py-1]     if wt in waitables and wt.is_ready(wait_set):
[simple_bdai.py-1]   File "/opt/ros/iron/lib/python3.10/site-packages/rclpy/event_handler.py", line 100, in is_ready
[simple_bdai.py-1]     if wait_set.is_ready('event', self._event_index):
[simple_bdai.py-1] IndexError: wait set index too big

**Comment by mhidalgo-bdai** [comment]
@dan9thsense hmm, I would bet a race condition. Exception is thrown [here](https://github.com/ros2/rclpy/blob/9536f8ec66020a552cf9ad421a11629ad8804a16/rclpy/src/rclpy/wait_set.cpp#L193-L195), suggesting the wait set changed and invalidated a waitable that is still around. 

I could use a minimum reproducible example here.

**Comment by jbarry-bdai** [comment]
@dan9thsense You could also try using the `ServiceHandle` wrapper around your service client but I'm not sure that will help.

**Comment by dan9thsense** [comment]
It's hard to create a minimum reproducible example because this happens during runs with a large gazebo sim along with MoveIt2, so a lot is going on.  It may well be a race condition, as it will happen intermittently-- sometimes occurs, sometimes doesn't, with the exact same code running.

Can you provide an example of how to properly wait for a service call with ros_utilities running? I've been avoiding using spin or spin_once in general, but to wait for a service, is it ok to use using spin_until_future_complete?

**Comment by mhidalgo-bdai** [comment]
> is it ok to use using spin_until_future_complete?

Hmm, if you followed `ros_utilities` documentation, you are using process-wide APIs. That means it is quite likely you are already spinning an executor in the background. So no, don't `spin_until_future_complete`. That'll bring another executor in, and they are not meant to cooperate.

Use `bdai_ros2_wrappers.futures.wait_for_future` on the future that a client returns on `call_async`. Or just `call`, that'll work too if you have an executor in background.

**Comment by dan9thsense** [comment]
At what rate do the nodes spin?  Is that a parameter I can set?  Do higher rates cost computation time?
One reason I'm asking is that I'd like to know this:  If I need a message callback to update to the latest message before using values in that message, how long do I have to wait to be sure that the node has been spun and updated?  I'd normally do that with spin_once() but since I don't want to compete with the process-wide waits, that is not an option.

**Comment by dan9thsense** [comment]
Can you provide an example of how to properly wait for a service call with ros_utilities running? 
 I see from your previous answer that I should not use spin_until_future_complete and now avoid that.  

what about: wait_for_service?
For example:

client.wait_for_service(timeout_sec=15.0)

**Comment by mhidalgo-bdai** [comment]
@dan9thsense sorry for the delay. I thought I had replied to your earlier comment.

> At what rate do the nodes spin? Is that a parameter I can set? Do higher rates cost computation time?

There is no fixed scheduling rate for the executor in `ros_utilities`, nor in any standard executor in ROS 2 for that matter. The net rate is a function of event rates, middleware latency, callback times, [callback grouping](https://docs.ros.org/en/rolling/How-To-Guides/Using-callback-groups.html), and executor design e.g. a single threaded executor cannot schedule and dispatch faster than it takes to execute the callbacks registered with it. 

When using `ros_utilities`, by default you are using a special kind of multi-threaded executor, one that uses a pool of threads that scales up and down with demand (based on an idle time threshold, not predictive). This [executor](https://github.com/bdaiinstitute/ros_utilities/blob/6cae62507e471578b8eba6154bec7a80a4f6a909/bdai_ros2_wrappers/bdai_ros2_wrappers/executors.py#L20-L49) is fully [configurable](https://github.com/bdaiinstitute/ros_utilities/blob/6cae62507e471578b8eba6154bec7a80a4f6a909/bdai_ros2_wrappers/bdai_ros2_wrappers/executors.py#L202-L232). Defaults should work just fine, but if you want to fine tune it, can check this [example](https://github.com/bdaiinstitute/ros_utilities/blob/6cae62507e471578b8eba6154bec7a80a4f6a909/bdai_ros2_wrappers/examples/tf_cli_example.py#L96-L115) on how to force a custom (configured) executor instance on `ros_utilities`. 

> If I need a message callback to update to the latest message before using values in that message, how long do I have to wait to be sure that the node has been spun and updated? I'd normally do that with spin_once() but since I don't want to compete with the process-wide waits, that is not an option.

Hmm, if you are using callbacks there is no need to wait for anything. I'll go on a leap and guess that you are trying to fetch messages synchronously. Provided you know you typically don't do that with ROS 2, and that you are here to go against those postulates :sweat_smile:, you may find [`bdai_ros2_wrappers.subscription.wait_for_message`](https://github.com/bdaiinstitute/ros_utilities/blob/6cae62507e471578b8eba6154bec7a80a4f6a909/bdai_ros2_wrappers/bdai_ros2_wrappers/subscription.py#L51) useful. Note it pretty much requires you to use `ros_utilities`.

> Can you provide an example of how to properly wait for a service call with ros_utilities running?

```python
client = node.create_client(ServiceType, "service_name")
client.wait_for_service(timeout_sec=5.0)
response = client.call(ServiceType.Request(), timeout_sec=10.0)
```

It is as simple as that. Most of the value that `ros_utilities` brings is that of enabling this kind of code without risking a hang.

**Comment by dan9thsense** [comment]
Thanks for the details.  That example service call is exactly what I am using and it does work.  I'm new to ROS2 and haven't gotten fully comfortable with the multi-threaded executors.  Also, I just didn't know if "wait_for_service" would create another executor in the way that "spin_until_future_complete" does.

To followup on my question about messages, I think that your suggestion with bdai_ros2_wrappers.subscription.wait_for_message will do the job but am wondering what you meant by "you typically don't try to fetch messages synchronously in ROS2."  What is the issue with that?

If you don't mind taking a moment to explain how you would deal with a specific case, I'd sure appreciate it.  Consider this scenario:  I want to pick up an object with a vacuum gripper.  I make the arm move down toward the object at, say 1 cm per step.  After each step, I check to see if the gripper has attached to the object by checking a subscribed topic message, something like "gripper_attached_state" that can be True or False.  Once the arm has touched the object, I want to stop moving it down so that it does not crush the object.  The question is, how can I be sure that the subscribed topic message has updated and is giving me correct information about the gripper state?  If the gripper state message has not updated, then I could be seeing a stale state, saying that the gripper has not attached and thus I would continue to move the arm down, crushing the object.  In the past, before ros_utilities, I solved this by forcing a check for a message update with "spin_once" and it seems that the ros_utilities call you suggested (bdai_ros2_wrappers.subscription.wait_for_message) would work fine.  However, I am wondering if I am going about this in the wrong way overall.  Is there a better way to to accomplish this sort of scenario?

**Comment by mhidalgo-bdai** [comment]
> what you meant by "you typically don't try to fetch messages synchronously in ROS2." What is the issue with that?

ROS 2 client libraries (and a good deal of the underlying stack) were written for asynchronous programming, using callbacks and futures. Executors wrap wait sets that poll for events in a loop, executors then take event data and invoke callbacks. Executors that use threads follow the same pattern, only that callback invocation is pushed to a thread pool. Writing synchronous, blocking code will almost always lead to deadlocks (if you wait for a message in a callback dispatched by a single threaded executor, it will never wake up, because blocking prevents further message dispatching in the first place), and thus it is discouraged. `ros_utilities` goes to some length to work around this.

> Is there a better way to to accomplish this sort of scenario?

Hmm, using `bdai_ros2_wrappers.subscription.wait_for_message` in a loop is perhaps the simplest if the end effector moves in discrete steps (using service calls, I presume?). You could use callbacks and futures, making asynchronous service calls from within the state subscription callback, checking the future status and end-effector state before trigger another call, but it is perhaps a bit convoluted. You're not trying to close any control loops here, so you can afford `wait_for_message` latency.

**Comment by dan9thsense** [comment]
Appreciate the insight. Thanks for you help!
