### ISSUE TITLE
how to wait until keyboard interrupt

### ISSUE THREAD

**Issue by dan9thsense** [bdaiinstitute/ros_utilities#65]
I sometimes want a node to run until I use Ctrl-C to make it stop.  My old way to do with was with spin_once() (see below).  If I can't use spin_once(), how to I do this?

Old way:

    try:
        rclpy.spin(node)  # Keep the node running until a shutdown signal is received
    except KeyboardInterrupt:
        node.get_logger().info('Keyboard interrupt received, shutting down.')

**Comment by jbarry-bdai** [comment]
Use `ros_process.wait_for_shutdown()`.  @mhidalgo-bdai we should probably add an example or something on the wiki for this.  the example we have uses `main.context.ok()` which i'm not sure still exists

**Comment by mhidalgo-bdai** [comment]
@jbarry-bdai +1 to the wiki example. Using `main.context.ok()` is still valid, though it only works with the executor in the foreground so you can do `spin_once` on it.

**Comment by dan9thsense** [comment]
Thanks!

**Comment by mhidalgo-bdai** [comment]
[Wiki](https://github.com/bdaiinstitute/ros_utilities/wiki/Process%E2%80%90wide-APIs#setting-up-single-node-processes) now briefly mentions `ros_process.wait_for_shutdown`.
