### ISSUE TITLE
how to assign a node name

### ISSUE THREAD

**Issue by dan9thsense** [bdaiinstitute/ros_utilities#82]
When creating a node as shown below, how do you give the node a name?  The default name seems to be the name of the class, with caps removed and an underscore inserted.  But looking through the source code, I cannot find a way to assign a specific name.  I do see an example with inheriting Node from bdai_ros2_wrappers.node but none when creating the node in the class.  Since I already have a lot of code written with the node created in the class, it would be good to not have to rewrite it all to inherit Node.

```
import bdai_ros2_wrappers.scope as ros_scope
import bdai_ros2_wrappers.process as ros_process

class TestNode():
    def __init__(self):
        self._node = ros_scope.node()
    def print_name(self):
        print(self._node.get_name())

@ros_process.main()
def main():
    test = TestNode()
    test.print_name()

if __name__ == '__main__':
    main()
```

Output:
```
test_node
```

**Comment by jbarry-bdai** [comment]
@mhidalgo-bdai context here is that user is running a script twice for two different robots and the nodes get the same name because it's taken from a file.  i know there's a way to pass a different name... can you comment?

**Comment by mhidalgo-bdai** [comment]
> The default name seems to be the name of the class, with caps removed and an underscore inserted.

As @jbarry-bdai said, it's not the name of the class, which `ros_process` has no way to know, but the basename of the file this code is in.

> When creating a node as shown below, how do you give the node a name? 

If you need to run multiple instances of the same program, just [remap the node name](https://docs.ros.org/en/rolling/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Nodes/Understanding-ROS2-Nodes.html#remapping):

```sh
ros2 run my_package test_node --ros-args -r __node:=test_node_1
ros2 run my_package test_node --ros-args -r __node:=test_node_2
```

It's even easier if you are using `launch`.

If you wanted to change the default process-wide node name, you can do that too by specifying a `prebaked` argument for `ros_process.main`, like:

```python
@ros_process.main(prebaked="my_node")
def main():
    ...
```

**Comment by dan9thsense** [comment]
It's not so easy to put them in a launch file or remap from ros run.  The nodes are being created inside a class and that class is imported into another script, so the node does not exist a the time of launching.  Since I need different node names for the same file, it does not work to change the process-wide node name.

**Comment by mhidalgo-bdai** [comment]
> The nodes are being created inside a class and that class is imported into another script

Hmm, this suggests a misunderstanding. Your `TestNode` class above is no node, it is using a node, the one in scope, which happens to be the process-wide node. Every instance of `TestNode` will do the same.

If you want a multi-node application, then you need to load multiple nodes. Check the [wiki](https://github.com/bdaiinstitute/ros_utilities/wiki). Also, looking at the `bdai_ros2_wrappers.process` and `bdai_ros2_wrappers.scope` modules will give you a better sense of what's possible with these utilities.

**Comment by dan9thsense** [comment]
I didn't understand that ros_process combines everything into a single node, so it does not make sense to "name" a node created with ros_process.
